#!/bin/bash

# Set environment variables for dev or CI
export APP_PORT=${APP_PORT:-80}

# These variables are not necessary for this project
export DB_PORT=${DB_PORT:-3306}
export DB_ROOT_PASS=${DB_ROOT_PASS:-secret}
export DB_NAME=${DB_NAME:-helpspot}
export DB_USER=${DB_USER:-helpspot}
export DB_PASS=${DB_PASS:-secret}
# end of unnecessary variables for the project

# Decide which docker-compose file to use
COMPOSE_FILE="dev"

# Disable pseudo-TTY allocation for CI (Jenkins)
TTY=""
STAGING_PATH=""

# Disable PROD_PATH to be able to work on deploy

if [ ! -z "$BUILD_NUMBER" ]; then
    COMPOSE_FILE="ci"
    TTY="-T"
fi

if [ ! -z "$PRODSTAGING" ]; then
    STAGING_PATH="/home/ubuntu/ci-concept-docker/"
    # TODO docker-compose for staging
    COMPOSE_FILE="dev"
    TTY="-T"
fi

REGULAR_PATH="docker-compose.$COMPOSE_FILE.yml"

COMPOSE="docker-compose -f $STAGING_PATH$REGULAR_PATH"

# If we pass any arguments...
if [ $# -gt 0 ];then

    # If "composer" is used, pass-thru to "composer"
    # inside a new container
    if [ "$1" == "composer" ]; then
        shift 1
        $COMPOSE exec $TTY \
            php \
            composer "$@"

    # If "test" is used, run unit tests,
    # pass-thru any extra arguments to php-unit
    elif [ "$1" == "test" ]; then
        shift 1
        $COMPOSE run --rm $TTY \
            #-w /var/www/html \
            php \
            ./vendor/bin/phpunit "$@"

    elif [ "$1" == "t" ]; then
        shift 1
        $COMPOSE exec $TTY \
            php \
            sh -c "cd /var/www/html && ./vendor/bin/phpunit $@"

    # If "npm" is used, run npm
    # from our node container
    elif [ "$1" == "npm" ]; then
        shift 1
        $COMPOSE run --rm $TTY \
            #-w /var/www/html \
            node \
            npm "$@"

    # If "gulp" is used, run gulp
    # from our node container
    elif [ "$1" == "gulp" ]; then
        shift 1
        $COMPOSE run --rm $TTY \
            #-w /var/www/html \
            node \
            ./node_modules/.bin/gulp "$@"
    else
        $COMPOSE "$@"
    fi
else
    $COMPOSE ps
fi
